build:
  stage: build
  script: 
    - echo "Generating the mazes"
    - python product/create_maze.py
    - echo "Mazes have been generated"

test:
  stage: test
  script: 
    - ls -l product/assets/images/characters/Dude_Monster/
    - python -m unittest discover ./product/testing/
