image: python:3.12

stages:
  - checkstyle
  - build
  - test

checkstyle:
  stage: checkstyle
  script:
    - python3.12 -m flake8

build:
  stage: build
  script:
    - echo "Generating the mazes"
    - python product/create_maze.py
    - echo "Mazes have been generated"
  artifacts:
    paths:
      - maze*

test:
  stage: test
  script:
    - ls -l product/assets/images/characters/Dude_Monster/
    - python -m unittest discover ./product/testing/
